parameters:
  modules:
    mainModule:
      files:
        - /apps/mainModule/services/bodyService.js
        - /apps/mainModule/services/userService.js
        - /apps/mainModule/services/menuItemService.js
        - /apps/mainModule/services/searchService.js
      dependencies:

    busModule:
      files:
        - /apps/busModule/busModule.js
      dependencies:

    logModule:
      files:
        - /apps/logModule/services/logService.js
      dependencies:
        - busModule

  bootstrap:
    modules:
      - mainModule
      - logModule
    services:
      - logService
      - userService
      - searchService
      - menuItemService
      - bodyService