fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media

indholdskanalen_main:
  resource: "@IndholdskanalenMainBundle/Resources/config/routing.yml"
  prefix:   /

JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /admin/jobs

itk_koba_integration:
  resource: "@ItkKobaIntegrationBundle/Resources/config/routing.yml"
  prefix:   /
